### ISSUE TITLE
MyNotes wont open

### ISSUE THREAD

**Issue by NusryNizam** [j4321/MyNotes#30]
I'm using Lubuntu 18.04 with XFCE. 
When I run `mynotes` in terminal, I get the following output:

```
Traceback (most recent call last):
  File "/usr/bin/mynotes", line 31, in <module>
    from mynoteslib.constants import save_config, PIDFILE
  File "/usr/lib/python3/dist-packages/mynoteslib/constants.py", line 352, in <module>
    TOOLKITS = get_available_gui_toolkits()
  File "/usr/lib/python3/dist-packages/mynoteslib/constants.py", line 344, in get_available_gui_toolkits
    os.path.join(PATH, "packages.tcl")]).decode().strip().split()
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tclsh': 'tclsh'
```

**Comment by j4321** [comment]
From the error message, it seems to me that you are missing the tcl package. I thought this package was a direct dependency of python3-tk but I have just checked and it is simply a suggested package. So I will add it to the dependency list. 

Thanks for reporting it and let me know if installing tcl solved the problem.

**Comment by NusryNizam** [comment]
@j4321 Thanks. Now it works!!
