### ISSUE TITLE
mynotes won't start

### ISSUE THREAD

**Issue by sispus** [j4321/MyNotes#36]
Hi,
I couldn't start mynotes.  I installed it from AUR on Manjaro KDE
```
Traceback (most recent call last):
  File "/usr/bin/mynotes", line 32, in <module>
    from mynoteslib.constants import save_config, PIDFILE
  File "/usr/lib/python3.8/site-packages/mynoteslib/constants.py", line 385, in <module>
    LANGUE = getdefaultlocale()[0].split('_')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```
How can I fix it?

**Comment by sispus** [comment]
Ok, my problem. Changing language from C fixed it.
